name: CI

on:
  push:
  pull_request:

jobs:
  core:
    name: Core PHP ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: ['8.2', '8.3', '8.4']
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - uses: ramsey/composer-install@v3
      - name: Check code style
        if: matrix.php == '8.2'
        run: composer cs
      - name: Run static analysis
        run: composer analyse
      - name: Run tests
        run: composer test
      - name: Check Rector
        run: composer rector
